# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6306c4ac082c93002fa99f89fb368c60930fff40923b44de0b41cff71080e5e768b435c8d400ce2c6bf3b58336c9b7924ee23946d4a7a766dad6aa681f489a5

test:
  secret_key_base: 6b90d5f64ee9b4b5f1bf0f525d43fff63aa31963a72228e8790b1f919e34c6aab471aa1a6e6c9cd5d00eea6def91f10967fa3b18ff131a91ba6204ee62441172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
